apiVersion: batch/v1
kind: Job
metadata:
  name: army-reference-collect-static
spec:
  template:
    metadata:
      name: army-reference-collect-static
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
      - name: app
        image: roguemichael/army-reference:190527B
        command: ["python", "manage.py", "collectstatic", "--noinput"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-key
                key: SECRET_KEY
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/cloud_storage/credentials.json
        volumeMounts:
          - name: google-cloud-credentials
            mountPath: /secrets/cloud_storage
            readOnly: true
      volumes:
      - name: google-cloud-credentials
        secret:
          secretName: google-cloud-credentials
      restartPolicy: Never
