apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: army-reference
  labels:
    app: army-reference
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: army-reference
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: app
          image: roguemichael/army-reference:190527B
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              path: /health/
              port: http
          readinessProbe:
            httpGet:
              path: /health/
              port: http
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: url
                  optional: true
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/cloud_storage/credentials.json
          volumeMounts:
            - name: google-cloud-credentials
              mountPath: /secrets/cloud_storage
              readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=fluent-service-241519:europe-west2:minis-dot-cool=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: google-cloud-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
      - name: google-cloud-credentials
        secret:
          secretName: google-cloud-credentials
