apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: army-reference
  labels:
    app: army-reference
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: army-reference
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: app
          image: roguemichael/army-reference:190521A
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: url
                  optional: true
        - name: db
          image: postgres:11.3-alpine
