apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: army-reference-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: minis-dot-cool-ip
    networking.gke.io/managed-certificates: minis-dot-cool-certificate
spec:
  rules:
  - host: minis.cool
    http:
      paths:
      - path: /*
        backend:
          serviceName: army-reference
          servicePort: 80
