# Generated by Django 2.2.1 on 2019-05-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warscroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armies.Game')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255)),
                ('weapon_type', models.CharField(choices=[('MELEE', 'Melee'), ('MISSILE', 'Missile')], max_length=15)),
                ('wording', models.TextField(blank=True)),
                ('warscroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armies.Warscroll')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255)),
                ('wording', models.TextField(blank=True)),
                ('warscroll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='armies.Warscroll')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
