# Generated by Django 2.2.1 on 2019-05-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('sub_phase', models.IntegerField(choices=[(0, 'Start'), (1, 'During'), (2, 'End')], default=1)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armies.Phase')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
