# Generated by Django 2.2.1 on 2019-05-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['phase', 'sub_phase', 'order']},
        ),
        migrations.AlterField(
            model_name='reference',
            name='sub_phase',
            field=models.IntegerField(choices=[(0, 'Start of phase'), (1, 'During phase'), (2, 'End of phase')], default=1),
        ),
    ]
